revert to 4 space indent

diff --git a/tocd b/tocd
--- a/tocd
+++ b/tocd
@@ -6,8 +6,8 @@ output_filename="$2"
 set -eu
 
 die() {
-  printf "%s\n" "$*" >&2
-  exit 1
+    printf "%s\n" "$*" >&2
+    exit 1
 }
 
 test -n "$input_filename"  || die "No input filename provided."
@@ -27,7 +27,7 @@ video_buffer_size_k=$(( 384 * 8 ))
 # Get video information
 #------------------------------------------------------------------------------
 duration_sec=$(ffprobe -v error -show_entries format=duration -of csv=p=0 \
-  "$input_filename" | cut -d, -f 1 | cut -d. -f1)
+    "$input_filename" | cut -d, -f 1 | cut -d. -f1)
 test -n "$duration_sec" || die "Can't get video duration."
 
 # Round video duration upwards
@@ -36,7 +36,7 @@ duration_sec=$(( duration_sec + 1 ))
 old_ifs=$IFS
 IFS=, read -r video_width video_height <<EOF
 $(ffprobe -v error -select_streams v:0 -show_entries stream=width,height \
-  -of csv=p=0 "$input_filename")
+    -of csv=p=0 "$input_filename")
 EOF
 IFS=$old_ifs
 
@@ -44,8 +44,9 @@ test -n "$video_width" || die "Can't get video width (no video stream?)."
 test -n "$video_height" || die "Can't get video height (no video stream?)."
 test "$video_height" -gt 0 || die "Invalid video height."
 if [ "$container_overhead_percent" -lt 1 -o \
-     "$container_overhead_percent" -gt 99 ]; then
-  die "Invalid container overhead value."
+    "$container_overhead_percent" -gt 99 ]; then
+
+    die "Invalid container overhead value."
 fi
 
 # Setup bitrates
@@ -59,22 +60,22 @@ output_width=640
 
 # Use lower resolutions for very low bitrates.
 if [ "$video_bitrate_k" -lt "500" ]; then
-  output_width=320
+    output_width=320
 elif [ "$video_bitrate_k" -lt "700" ]; then
-  output_width=512
+    output_width=512
 fi
 
 # Cap bitrate to a supported value.
 if [ "$video_bitrate_k" -gt "$average_video_bitrate_k" ]; then
-  printf "==> Average video bitrate of %dk is too high, lowering to %dk\n" \
-    "$video_bitrate_k" "$average_video_bitrate_k" >&2
-  video_bitrate_k="$average_video_bitrate_k"
+    printf "==> Average video bitrate of %dk is too high, lowering to %dk\n" \
+        "$video_bitrate_k" "$average_video_bitrate_k" >&2
+    video_bitrate_k="$average_video_bitrate_k"
 fi
 
 # Setup aspect ratio
 #------------------------------------------------------------------------------
 round_to_next_16() {
-  echo $(( ($1 + 15) / 16 * 16 ))
+    echo $(( ($1 + 15) / 16 * 16 ))
 }
 
 fixed_point_scale=100
@@ -84,9 +85,9 @@ output_height=$( round_to_next_16 $output_height )
 resolution="${output_width}:${output_height}"
 
 if [ "$output_width" -lt 640 ]; then
-  printf "==> Video bitrate of %dk is too low,\n" "$video_bitrate_k" >&2
-  printf "==> lowering resolution to %dx%d.\n" \
-    "$output_width" "$output_height" >&2
+    printf "==> Video bitrate of %dk is too low,\n" "$video_bitrate_k" >&2
+    printf "==> lowering resolution to %dx%d.\n" \
+        "$output_width" "$output_height" >&2
 fi
 
 video_filter="-vf scale=${resolution}:flags=lanczos"
@@ -117,11 +118,11 @@ audio_options="$audio_options -af acompressor,loudnorm=I=-16:LRA=11:TP=-1.5"
 
 # shellcheck disable=SC2086
 ffmpeg $common_options -i "${input_filename}" \
-  $video_options -an -pass 1 -y /dev/null
+    $video_options -an -pass 1 -y /dev/null
 
 # shellcheck disable=SC2086
 ffmpeg $common_options -i "${input_filename}" \
-  $video_options $audio_options -pass 2 -y "${output_filename}"
+    $video_options $audio_options -pass 2 -y "${output_filename}"
 
 rm -f ffmpeg2pass-0.log*
 
@@ -129,5 +130,5 @@ printf "==> Unpacking b-frames\n"
 temp_file=$(mktemp)
 # shellcheck disable=SC2086
 ffmpeg $common_options -i "${output_filename}" -c copy \
-  -bsf:v mpeg4_unpack_bframes -f avi -y "${temp_file}"
+    -bsf:v mpeg4_unpack_bframes -f avi -y "${temp_file}"
 mv -f "${temp_file}" "${output_filename}"
